version: '3.8'
networks:
  app_networks:
    driver: bridge


services:
  app:
    image: mipowka/bot-news-image
    ports:
      - "9090:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/habr_news
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
    networks:
      - app_networks



  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: habr_news
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    restart: always
    networks:
      - app_networks

