spring:
  application:
    name: NewsService

  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop

logging:
  level:
    root: info
    org.springframework.web: DEBUG
  file:
    name: logs/application.log